name: run main.py

on:
  push:
  schedule:
    - cron: '* * * * *'     # script to run every minute? Actions schedule run at most every 8 minutes roughly.


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: execute python script
        run: python3 main.py

      - name: commit files
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        
        with:
          # if this works it is done manually, I haven't declared the variable GITHUB_TOKEN!
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
